### ISSUE TITLE
Use font-weight numbers instead of keywords

### ISSUE THREAD

**Issue by drewbarontini** [mvcss/mvcss#25]
For font weights, should it be `$t-fontWeight-400`/`tw400` or `$t-fontWeight-normal`/`twn` but use `400` and other keywords as the value?

**Comment by johndjameson** [comment]
I'm all for the number-based approach. They're consistent and easier to read/maintain once you pick up the syntax.

We can probably kill the variables since 100, 300, etc. are keywords in CSS. Variables like `$t-fontWeight-400` only duplicate static values.

And we can drop the trailing zeros in class names because they're implied.

```
.mv-tw1
  font-weight: 100
.mv-tw3
  font-weight: 300
.mv-tw4
  font-weight: 400
.mv-tw6
  font-weight: 600
.mv-tw7
  font-weight: 700
.mv-tw8
  font-weight: 800
.mv-tw9
  font-weight: 900
```

This also addresses the issue of different fonts calling their values different names. One font might be "light" at 200 while another font is "light" at 300. Trying to use both with named variables can get icky.

:+1::question:

**Comment by drewbarontini** [comment]
Good call. I agree with this :+1:
