### ISSUE TITLE
Power Tools

### ISSUE THREAD

**Issue by drewbarontini** [mvcss/mvcss#8]
Idea from @johndjameson to `!important` all tool classes.

**Comment by nickawalsh** [comment]
Super clever title notwithstanding, I'd shy away from this. A tool not working is a pretty good indication of cleanup needed elsewhere.

**Comment by drewbarontini** [comment]
That's my general viewpoint as well, but figured the idea at least warranted a more formal discussion.

**Comment by nickawalsh** [comment]
You'd be reckless *not* opening an issue with that title.

**Comment by johndjameson** [comment]
We don't reach for `!important` on tools very often, but some modules can't be reasonably refactored. Our approach right now is to create a unique structure or a modifier of a modifier, and then author the styles under that namespace. Doing this works, but creates otherwise reusable styles that could work in other contexts.

We intend tools to act authoritatively, and bolstering their specificity does the trick and doesn't seem to have any _real downsides_.

Using `!important` elsewhere:

- https://github.com/suitcss/utils-text/blob/master/lib/text.css
- https://github.com/inuitcss/trumps.spacing/blob/master/_trumps.spacing.scss
- https://speakerdeck.com/dafed/managing-css-projects-with-itcss?slide=62

**Comment by drewbarontini** [comment]
I honestly could argue it either way, and I don't have strong enough opinions _not_ to do it. I don't encounter the problem often, but sometimes having `!important` on the tool class would be easier than creating an all-new modifier for a one-off instance.

**Comment by drewbarontini** [comment]
@dangodev You're a fan of implementing this?

**Comment by dangodev** [comment]
@drewbarontini absolutely not. I just enjoyed Nick’s comment.

**Comment by drewbarontini** [comment]
Seems like we aren't in agreement on this, so we'll close it for now and bring it up for discussion later, should the need arise again.
